# Workflow to build and upload archives to GitHub release. Triggered by pushing
# a new tag.
name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build release files
        run: |
          python3 create_smod.py

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            soldat.smod
            client.zip
            server.zip
          body: Soldat assets.
          name: Soldat assets ${{ github.ref_name }}
